# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
