# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200418_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('list', 'text')]),
        ),
    ]
